# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hypeman < Formula
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/onkernel/hypeman"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/onkernel/hypeman-cli/releases/download/v0.6.2/hypeman_0.6.2_macos_amd64.zip"
      sha256 "6974b940a68dc17a3450c1451c6272307f2fe09def19c9cf77ddbc987b6e9768"

      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/onkernel/hypeman-cli/releases/download/v0.6.2/hypeman_0.6.2_macos_arm64.zip"
      sha256 "7347675066214424645c7ea1b59d5b24a298ae6cf4f06a5974bbcfae4d431987"

      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/onkernel/hypeman-cli/releases/download/v0.6.2/hypeman_0.6.2_linux_amd64.tar.gz"
      sha256 "e1b40014dc4deee43948c724c92d00e6c8780c5eb8755489534d03d2d503bc3f"
      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/onkernel/hypeman-cli/releases/download/v0.6.2/hypeman_0.6.2_linux_armv6.tar.gz"
      sha256 "22d66de39512a3b5e8c05a05d03f5555730d0554bf93522790291c03423802fa"
      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/onkernel/hypeman-cli/releases/download/v0.6.2/hypeman_0.6.2_linux_arm64.tar.gz"
      sha256 "dc612e5312378bbb469c93eb4d2655aef3e7963a8a7e72ffcfb8b13372f92ffd"
      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/hypeman", "--version"
  end
end
