# This file was generated by GoReleaser. DO NOT EDIT.
cask "hypeman" do
  name "hypeman"
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/onkernel/hypeman"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hypeman"
  manpage "man/man1/hypeman.1.gz"
  bash_completion "completions/hypeman.bash"
  zsh_completion "completions/hypeman.zsh"
  fish_completion "completions/hypeman.fish"

  on_macos do
    on_intel do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_macos_amd64.zip"
      sha256 "d2cce9e915384cf3a7bcba9f35e0340b22629b1488cfe3390a52ce5998b76420"
    end
    on_arm do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_macos_arm64.zip"
      sha256 "bfe396693f2033a83f161fe8f5617e01fd89caeff5b7cb940e666f4bba52dc27"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_linux_amd64.tar.gz"
      sha256 "cafbaf5384af2efc710b98134ca54c5e21955f83ac1262df4c276307f1b74d95"
    end
    on_arm do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_linux_arm64.tar.gz"
      sha256 "4dd48e9199ea9de99e660fdb62ad8ae26ce3005f7b2a2b47fc4d7e85f40ee6e9"
    end
  end

  # No zap stanza required
end
