# This file was generated by GoReleaser. DO NOT EDIT.
cask "hypeman" do
  name "hypeman"
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/onkernel/hypeman"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hypeman"
  manpage "man/man1/hypeman.1.gz"
  bash_completion "completions/hypeman.bash"
  zsh_completion "completions/hypeman.zsh"
  fish_completion "completions/hypeman.fish"

  on_macos do
    on_intel do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_macos_amd64.zip"
      sha256 "3120ee34b922e4bd1b4398292c5baf23cdffb5a3288cd571a1c6d3cbe8eb1f6a"
    end
    on_arm do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_macos_arm64.zip"
      sha256 "f2e3175da3898892d80fb5717ad104de7d76d81b496e9f976910a0764abe7b08"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_linux_amd64.tar.gz"
      sha256 "1acdb8d72ad57f60e31c44234658d029437d5948d311b4b035e0cdd402ab5902"
    end
    on_arm do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_linux_arm64.tar.gz"
      sha256 "901a08f2385e24782185d782d8ef14c9ee3f24f2d258d29d2c73a5cfb763236c"
    end
  end

  # No zap stanza required
end
