# This file was generated by GoReleaser. DO NOT EDIT.
cask "hypeman" do
  name "hypeman"
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/onkernel/hypeman"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hypeman"
  manpage "man/man1/hypeman.1.gz"
  bash_completion "completions/hypeman.bash"
  zsh_completion "completions/hypeman.zsh"
  fish_completion "completions/hypeman.fish"

  on_macos do
    on_intel do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_macos_amd64.zip"
      sha256 "8504c82b059c8df6141d68f111108f1b3af2db8b32d985c9fc945d9c6c0a0c27"
    end
    on_arm do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_macos_arm64.zip"
      sha256 "e6674e899874016b13c9953cb762ee7f736b1183a633d66283cd6f6a1c77f5b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_linux_amd64.tar.gz"
      sha256 "3fc5b47abdba7794ff3ebfaed26f9597ba7469e5cb6c6c715ddbd10c09beef9e"
    end
    on_arm do
      url "https://github.com/onkernel/hypeman-cli/releases/download/v#{version}/hypeman_#{version}_linux_arm64.tar.gz"
      sha256 "32b7e8a75555bb6e9c07e134023b56c24032a04e7f13be34242d5501f2ed35b6"
    end
  end

  # No zap stanza required
end
