# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hypeman < Formula
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/kernel/hypeman"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.12.0/hypeman_0.12.0_macos_amd64.zip"
      sha256 "00b9daf4c0b35136381e91ab3d7e3130da2b24b3ee1cba1b81cf87df17572dfe"

      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.12.0/hypeman_0.12.0_macos_arm64.zip"
      sha256 "0aae15f403dfcbc0ee5460453f065cd067cb61bf07bc08c60e900c05e550bda0"

      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.12.0/hypeman_0.12.0_linux_amd64.tar.gz"
      sha256 "372319a10c78c4a27d9d7c6dbbc2dd0483f668ba42287f430c9dab45d66ea88b"
      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.12.0/hypeman_0.12.0_linux_armv6.tar.gz"
      sha256 "1a91b0367c10ef1113297e28344534220f2873ddaf17d21f0d91b77c990510ca"
      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.12.0/hypeman_0.12.0_linux_arm64.tar.gz"
      sha256 "110fbf004a29a316d070d286a57e8c5b88370989208d791093de7c6a16bb27cf"
      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/hypeman", "--version"
  end
end
