# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hypeman < Formula
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/kernel/hypeman"
  version "0.9.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.9.2/hypeman_0.9.2_macos_amd64.zip"
      sha256 "600ba367e8aa2910e501837f61ffa993ae5a9362b4279a0c5d72bae27a9c5190"

      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.9.2/hypeman_0.9.2_macos_arm64.zip"
      sha256 "44c4bd8079b64fa8188287170a241f1fa93281378f93f077c81fe450e38acd92"

      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.9.2/hypeman_0.9.2_linux_amd64.tar.gz"
      sha256 "d23fab6038463d8bf040038e2e6cec00b3d39d0a83ca5b7ff0b9db2734d3a7ce"
      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.9.2/hypeman_0.9.2_linux_armv6.tar.gz"
      sha256 "7ccf83a18280a6164b4449760c19e4eeb3f44cb0a66fd03d31bd37f9de9c5ef2"
      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.9.2/hypeman_0.9.2_linux_arm64.tar.gz"
      sha256 "37912c2f60ab7565d74c97700b386a0fc89e5486d96d26f9e1d712120af0ced9"
      def install
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/hypeman", "--version"
  end
end
