# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hypeman < Formula
  desc "orchestrate cloud-hypervisor VMs"
  homepage "https://github.com/kernel/hypeman"
  version "0.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.14.0/hypeman_0.14.0_macos_amd64.zip"
      sha256 "4d851e90c7cf5a0558aea0fc4f575786cfd5fb61ae7344a5ca8f59d9daab5ffa"

      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.14.0/hypeman_0.14.0_macos_arm64.zip"
      sha256 "8dc8ba2b0f992030b705dcf11096fb670c0c4532887f6dbbbcf15cc6d3ebd0ba"

      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.14.0/hypeman_0.14.0_linux_amd64.tar.gz"
      sha256 "4100952f3c04cb9a18de326cfd20da830efb620dd9f0ffb91ab75d296682a2b5"
      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.14.0/hypeman_0.14.0_linux_armv6.tar.gz"
      sha256 "d8162ec249dab4ba0dc9a727f888b57193342b94377af4e5acb08293c2bd2efd"
      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/hypeman-cli/releases/download/v0.14.0/hypeman_0.14.0_linux_arm64.tar.gz"
      sha256 "9ddc569e2936e5f455049952bd62b38beea63fb3e1f5bcf86c58d52cf8d0e06e"
      define_method(:install) do
        bin.install "hypeman"
        bash_completion.install "completions/hypeman.bash" => "hypeman"
        zsh_completion.install "completions/hypeman.zsh" => "_hypeman"
        fish_completion.install "completions/hypeman.fish"
        man1.install Dir["man/man1/*.1.gz"]
      end
    end
  end

  test do
    system "#{bin}/hypeman", "--version"
  end
end
