# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lw < Formula
  desc "CLI for the Leaseweb API"
  homepage "https://github.com/kernel/leaseweb-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.2.1/lw_0.2.1_macos_amd64.zip"
      sha256 "ef76b63817d2d0a4975794986cfdcf0da1e1af419f6dc81c03e6cd1209cc89da"

      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.2.1/lw_0.2.1_macos_arm64.zip"
      sha256 "d52d99a04979a4c564f3d72c0af5218017c18efe954748c9079d2de774478817"

      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.2.1/lw_0.2.1_linux_amd64.tar.gz"
      sha256 "060db5eab29f1d425b38fc7666c08f6ada407b4a934d5ccf3206ea4976c83549"
      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.2.1/lw_0.2.1_linux_armv6.tar.gz"
      sha256 "1c3bfbbc3af45d69e0d0dff3b9287388b52a0187fc8773da707bc45ac7eb5dbc"
      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.2.1/lw_0.2.1_linux_arm64.tar.gz"
      sha256 "6f904d60ec687cefaa83f9d0013731f8d280c2054a4a27738e4aec190c32a1fc"
      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
  end

  test do
    system "#{bin}/lw", "--version"
  end
end
