# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lw < Formula
  desc "CLI for the Leaseweb API"
  homepage "https://github.com/kernel/leaseweb-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.1.0/lw_0.1.0_macos_amd64.zip"
      sha256 "b9b83dd9a34618106ac123b97f71ad2840abddb2d5245303bf1d5521acdcec7a"

      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.1.0/lw_0.1.0_macos_arm64.zip"
      sha256 "8ae3b3454e2c845cf79f336fb192229c44e12ac84bcd4d7f56e6c538c0fe929c"

      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.1.0/lw_0.1.0_linux_amd64.tar.gz"
      sha256 "fac757a7b18fde575ccdb916a6468d6425a2a59b9342bfeb30e78afc452b93aa"
      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.1.0/lw_0.1.0_linux_armv6.tar.gz"
      sha256 "7604f5a383d45f830e5a7aa85e39215c62ac49c74b48b4a9ec0fd086b668f57f"
      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel/leaseweb-cli/releases/download/v0.1.0/lw_0.1.0_linux_arm64.tar.gz"
      sha256 "01c15f3c1f125956eb1c71c37493cd560717ac674689fc410ccc1625ca68895a"
      define_method(:install) do
        bin.install "lw"
        bash_completion.install "completions/lw.bash" => "lw"
        zsh_completion.install "completions/lw.zsh" => "_lw"
        fish_completion.install "completions/lw.fish"
      end
    end
  end

  test do
    system "#{bin}/lw", "--version"
  end
end
